import type { Metadata } from "next";
import {  Lora, JetBrains_Mono, Bitter } from "next/font/google";
import "./globals.css";


const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

const jetbrains = JetBrains_Mono({
  variable: "--font-jet",
  subsets: ["latin"],
});

const bitter = Bitter({
  variable: "--font-bitter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Oi Viana - Archives",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${lora.variable} ${jetbrains.variable} ${bitter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
